language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - npm run heroku-postbuild

deploy:
  provider: heroku
  api_key:
    secure: "ewYtVki3vFgzbZSxuZX3UbwN1fv1dMhhnxfKRr8ogjhcldpENbti1HPrPM5eTowoqoXkAge4v0VJ3qv/Pu/RXzaCx+/cXhEsOUhjCvX98M0r1bch0cYloyBSUSmGT+iSXmr0IafQHKolN6MfeqybZeofsVv5h5iGFHtVF8KrDbvJvTwu2WJNb1salRnL7bfQBAq6JC1jvDMo3HpfPQACGyA9Rj6mfvS0e45+VE0JtUBKP5lXUEsh010BxSlAvx7VYGeh1zBN85Ncpg+3sbl1za0u+WNsE62lMHJksplXEIX8URJVpECD2ErEE1LKVWURjPt4YMD57KreEe6bSNQdahsT+27RhlUaVtPEKhhh0hfoxAvOsEqkkMrsNjlIlk8hwuPrXn6OvUBs/cmvBHcISIm+5ptDankg6jTcIumXCQk/r9NI/g6SaT+/SggB2Ww0NFbRuousutXvwISn4YqGPTng9345Fz5F/yBun80PTMTkuOuvwQFghwRYh5xtW4n3aobARcUaBMcz6Zocp1JemTbXSO03Q8JqQoIvJa99wm4KLuxfQKV/8oH0e3U/RgLzIWrYaOcUEeCCwmvfmH7u9aWHLYxPBUGK7C5bXFOpPby6i46n6ILnygjH0hczTeFp8fnmBSmFtMyCzxBk2ApQKRT9bzTLNO9trJTpctfX6qg="
  app: warm-brushlands-44749
  on:
    repo: mytinerary-app
