version: "3"

services:
  backend:
    image: mytin-backend
    restart: always
    build: .
    env_file: .env
    ports:
      - "5000:5000"
  client:
    image: mytin-client
    build: ./client
    restart: always
    ports:
      - "3000:3000"
    links:
      - backend
    depends_on:
      - backend
