export const GET_CITIES = "GET_CITIES"
export const ADD_CITY = "ADD_CITY"
export const DELETE_CITY = "DELETE_CITY"
export const ADD_SUCCESS = "ADD_SUCCESS"
export const CITIES_LOADING = "CITIES_LOADING"
export const GET_ITINERARIES = "GET_ITINERARIES"
export const ITINERARIES_LOADING = "ITINERARIES_LOADING"
export const ADD_ITINERARY = "ADD_ITINERARY"
export const ADD_IT_SUCCESS = "ADD_IT_SUCCESS"
export const GET_ACTIVITIES = "GET_ACTIVITIES"
export const ACTIVITIES_LOADING = "ACTIVITIES_LOADING"
export const UPDATE_CITY = "UPDATE_CITY"
export const ADD_ACTIVITY = "ADD_ACTIVITY"
export const ADD_AC_SUCCESS = "ADD_AC_SUCCESS"





